[build]
  command = "npm install && npm run build"
  publish = ".next"
  edge_functions = "edge-functions"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://ai-prompt-tutor-image.netlify.app"
  NODE_VERSION = "18"
  NEXT_PUBLIC_RUNTIME = "edge"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    isProprietary = true
    experimentalBundling = true

[[edge_functions]]
  included_files = ["src/lib/**"]
  function = "next-server"
  path = "/*"

[functions]
  directory = "edge-functions"
  external_node_modules = ["@netlify/functions"]

[functions]
  included_files = ["src/lib/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
