[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://ai-prompt-tutor-image.netlify.app"
  NODE_VERSION = "18"
  NEXT_PUBLIC_RUNTIME = "edge"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/lib/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
