[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://ai-prompt-tutor-image.netlify.app"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  directory = "edge-functions"
  included_files = ["src/lib/**"]
  external_node_modules = ["@netlify/functions"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
